### ISSUE TITLE
Add Hacktoberfest tag

### ISSUE THREAD

**Issue by lfmundim** [ClydeDz/horoscope-nuget#11]
## Select type of issue

- [ ] Bug
- [X] Feature request 

## If it's a feature request...
**Please explain your request and why you'd like to see it in this service.**    
Include the `hacktoberfest` tag so PRs on this can count for the event! I actually enjoy this repo and would like to add a new feature to it, specially if it would count as a contribution for Hacktoberfest :)

**Comment by ClydeDz** [comment]
Hey, @lfmundim, 

That's great! Did you have any features in mind for this NuGet package? If so, could you please open an issue for what you have in mind and we can probably discuss it there before you implement it away. 

Re the tag, did you mean to add a topic on the repo? I've added `hacktoberfest` now. Feel free to close this issue if that's what you intended. 

Thanks!
